# Generated by Django 4.2.2 on 2023-06-17 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.CreateModel(
            name='Reporting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('report', models.CharField(choices=[('I', 'Internet'), ('N', 'Newspaper'), ('P', 'Press Conference'), ('T', 'Television')], default='I', max_length=1)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.case')),
            ],
        ),
    ]
