# Generated by Django 4.2.2 on 2023-06-17 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_reporting_options_remove_case_declassified_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('location', models.CharField()),
                ('comments', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='testimonies',
            field=models.ManyToManyField(to='main_app.testimony'),
        ),
    ]
