# Generated by Django 4.2.2 on 2023-06-18 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_testimony_case_testimonies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimony',
            name='comments',
            field=models.CharField(),
        ),
    ]
