# Generated by Django 4.2.2 on 2023-06-20 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_case_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporting',
            name='report',
            field=models.CharField(choices=[('D', 'Documentary'), ('I', 'Internet'), ('N', 'Newspaper'), ('P', 'Press Conference'), ('T', 'Television')], default='D', max_length=1),
        ),
    ]
