# Generated by Django 4.2.2 on 2023-06-21 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='news',
        ),
    ]
